settings:
  headers:
    Content-Type: application/x-www-form-urlencoded; charset=UTF-8
  sysSetting:
    user: tdtest
    pwd: 1qaz@WSX
  openapi_dev:
    ip: localhost
    port: 8080
  openapi_prod:
    ip: aladdin.zj.chinamobile.com
    port: 80
  openapi_test:
    ip: 10.70.194.177
    port: 80

sys:
  tdtest:
    appkey: tdtest
    city: 571
    county: 571A
    industry: 01

apis:
#  新建模板
  CrtTpl:
    type: post
    url: /openapi/template/new
    body:
      sys:
      channelId: SMSPAAS
      modelTitle: 喜传单
      modelSign: 喜传单
      location: 0
      modelContent: 2M微端，2秒下载！2018最经典传奇终于回归！装备全爆端游品质！{$var1}，退订回T
#  新建活动
  CrtAct:
    type: post
    url: /openapi/activities/new
    body:
      sys:
      channelId: CMPP
      actName: test9
      cgpId: 339
      contentType: 1
      sendContent: d2f0ed49-2a73-40ec-85c2-01d4100b67a9
      sendCnt: 999
      sendMethod: 1
      triggerCon: 2018-07-27 11:08:00
      fromNo: 10658618999
      isBid: Y
#  新建竞价活动
  CrtBidAct:
    type: post
    url: /openapi/activities/bid/new
    body:
      sys:
      busiId: 2
      actName: 百度
      sendContent: 百度一下，你就知道${var1}
      sendStartDate: 2018-08-01
      sendEndDate: 2018-08-01
      sendStartTime: 08:00:00
      sendEndTime: 23:59:59
      limitAmt: 10000
      price: 0.01
      isRealtime: 1
      originUrl: https://www.baidu.com
      ruleStr: '#98260<20'
      sites: '[{"opera":"or","latitude":"30.321228350169445","ptype":"all","radius":"1000","longitude":"120.0681886350031"}]'
#  修改竞价状态
  EBidStatus:
    type: post
    url: /openapi/activities/bid/status/modify/
    body:
      sys:
      actId: 104
      status: cancel
#  修改竞价价格
  EBidPrice:
    type: post
    url: /openapi/activities/bid/price/modify/
    body:
      sys:
      price: 0.01
      actId: 104
#  查询竞价结果
  GetBidInfo:
    type: get
    url: /openapi/activities/bid/result/
    body:
      sys:
      param: 104
#  查询实时竞价结果
  GetCurrentBidInfo:
    type: get
    url: /openapi/activities/bid/current/result/
    body:
      sys:
      param: 104
#  查询竞价状态
  GetBidActInfo:
    type: get
    url: /openapi/activities/bid/
    body:
      sys:
      param: 104
#  洞察类
  GetActInfo:
    type: get
    url: /openapi/activities/result/
    body:
      sys:
      param: 194
#  查询标签信息
  GetTagsInfo:
    type: get
    url: /openapi/tags/
    body:
      sys:
      param: LG02




