settings:
  headers:
    Content-Type: 'application/x-www-form-urlencoded; charset=UTF-8'
  sysSetting:
    tdtest: '1qaz@WSX'
    santikeji: '1qaz@WSX'
    asiainfojj: '1qaz@WSX'
  dev:
    ip: 'localhost'
    port: '8080'
  prod:
    ip: 'aladdin.zj.chinamobile.com'
    port: '80'
  test:
    ip: '10.70.194.177'
    port: '80'

sys:
  tdtest:
    appkey: 'tdtest'
    city: '571'
    county: '571A'
    industry: '01'
  santikeji:
    appkey: 'santikeji'
    city: '571'
    county: '571A'
    industry: 'LG11'
  asiainfojj:
    appkey: 'asiainfojj'
    city: '571'
    county: '571A'
    industry: '01'

#api名称最好控制在6位
apis:
  CrtTpl:
    name: '新建模板'
    type: 'post'
    url: '/openapi/template/new'
    body:
      sys: ''
      channelId: 'SMSPAAS'
      modelTitle: 'title'
      modelSign: 'sign'
      location: '0'
      modelContent: 'content'
  CrtAct:
    name: '新建活动'
    type: 'post'
    url: '/openapi/activities/new'
    body:
      sys: ''
      channelId: 'CMPP'
      actName: 'test'
      cgpId: '339'
      contentType: '1'
      sendContent: 'd2f0ed49-2a73-40ec-85c2-01d4100b67a9'
      sendCnt: '999'
      sendMethod: '1'
      triggerCon: '2018-07-27 11:08:00'
      fromNo: '10658618999'
      isBid: 'Y'
  CrtBid:
    name: '新建竞价活动'
    type: 'post'
    url: '/openapi/activities/bid/new'
    body:
      sys: ''
      busiId: '2'
      actName: '百度'
      sendContent: '百度一下，你就知道${var1}'
      sendStartDate: '2018-08-01'
      sendEndDate: '2018-08-01'
      sendStartTime: '08:00:00'
      sendEndTime: '23:59:59'
      limitAmt: '10000'
      price: '0.01'
      isRealtime: '1'
      originUrl: 'https://www.baidu.com'
      ruleStr: '#98260<20'
      sites: '[{"opera":"or","latitude":"30.321228350169445","ptype":"all","radius":"1000","longitude":"120.0681886350031"}]'
  EBidSt:
    name: '修改竞价状态'
    type: 'post'
    url: '/openapi/activities/bid/status/modify/'
    body:
      sys: ''
      actId: '104'
      status: 'cancel'
  EBidPr:
    name: '修改竞价价格'
    type: 'post'
    url: '/openapi/activities/bid/price/modify/'
    body:
      sys: ''
      price: '0.01'
      actId: '104'
  GBidIf:
    name: '查询竞价结果'
    type: 'get'
    url: '/openapi/activities/bid/result/'
    body:
      sys: ''
      param: '104'
  GCBdIf:
    name: '查询实时竞价结果'
    type: 'get'
    url: '/openapi/activities/bid/current/result/'
    body:
      sys: ''
      param: '104'
  GBdAIf:
    name: '查询竞价状态'
    type: 'get'
    url: '/openapi/activities/bid/'
    body:
      sys: ''
      param: '104'
  GActIf:
    name: '洞察类'
    type: 'get'
    url: '/openapi/activities/result/'
    body:
      sys: ''
      param: '194'
  GTagIf:
    name: '查询标签信息'
    type: 'get'
    url: '/openapi/tags/'
    body:
      sys: ''
      param: 'LG02'




